### ISSUE TITLE
OPTIONS http://www.cepaberto.com/api/v3/cep?cep=29040040 404 (Not Found)

### ISSUE THREAD

**Issue by diogoaltoe** [edumucelli/cepaberto-api-examples#15]
Olá! Estou tentando consumir o WS com o React, porém estou tendo problemas para retornar o json via browser.
A consulta funciona utilizando um cliente, tipo o Postman, porém pelo browser não.

Segue mensagem de erro:
<pre>
Failed to load http://www.cepaberto.com/api/v3/cep?cep=29040040: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
</pre>

O fonte do cliente:

<pre>
...
            const api = create({
                baseURL: 'http://www.cepaberto.com/api/v3',
                //timeout: 10000,
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': 'Token token=XXXXXXXXXXXXXXXXXXXXX,
                }
            });

            // start making calls
            const response = await api.get(                
                '/cep',
                {},
                {
                    params: {
                        cep: this.state.cep.replace('-', '').replace('.', '')
                    }
                }
            );
...
</pre>

Pelo que parece o problema tem a ver com o CORS e com o método OPTIONS.
Já tentei configurar outros atributos no Header mais sem sucesso...

Alguém tem alguma sugestão?

**Comment by renantins** [comment]
@diogoaltoe estou com o mesmo problema aqui, mas estou usando Angular.

**Comment by isaacboratino** [comment]
Achei uma forma de resolver o cors quando chamamos atraves de localhost usando o heroku, dessa forma

baseURL: 'https://cors-anywhere.herokuapp.com/https://www.cepaberto.com/api/v3'

Então é so fazer a consulta tipo
https://cors-anywhere.herokuapp.com/https://www.cepaberto.com/api/v3/cep?cep=9983289

**Comment by mmendesx** [comment]
Cê conseguiu resolver?
Também tô com o mesmo problema

**Comment by diogoaltoe** [comment]
Eu acabei aderindo a API do Google para resolver a questão de endereços e localização geoespacial.

**Comment by edumucelli** [comment]
O CEP Aberto não tem CORS habilitado.

**Comment by luizfeer** [comment]
Se você chegou aqui desista. Desabilitar o cors no navegador limita o header, não sendo possível enviar o Token. Se o cors é um problema aceitar o token via params seria um caminho.
Infelizmente o cep-aberto não é tão aberto assim. O jeito e encher mais o google com dinheiro.
