### ISSUE TITLE
Busca de Latitude e Longitude

### ISSUE THREAD

**Issue by daniloalves19** [edumucelli/cepaberto-api-examples#19]
Bom dia,

Ao utilizar esta rota [https://www.cepaberto.com/api/v3/cep?cep=14402040](url) os dados de endereço estão corretos, porém a latitude e longitude estão sendo retornadas erradas.

Endereço: RUA LUIZ CHRYSOGONO DE CASTRO
Latitude/Longitude retornada: -20.5393288 e -47.4013437.
Porém estas coordenadas são da RUA SALDANHA MARINHO, no centro da cidade, distantes 5km uma da outra
A Latitude/Longitude correta seria -20.518379, -47.374264

Como estas coordenadas são retornadas pela API? É consumida outra api ou atualizada por colaboração da comunidade?

**Comment by edumucelli** [comment]
Você pode editar a latitude e longitude deste CEP posicionando o marcador no map no lugar que você considera mais correto: https://cepaberto.com/ceps/190696/edit
