### ISSUE TITLE
Exemplo de uso da API do CEP Aberto em PHP

### ISSUE THREAD

**Issue by FernandoCelmer** [edumucelli/cepaberto-api-examples#22]
Olá, realizei um  pull request (https://github.com/edumucelli/cepaberto-api-examples/pull/20/commits/dd5d9123720bbeaa736406c467d4efa83ac124ff) no repositório https://github.com/edumucelli/cepaberto-api-examples, teria como vocês realizarem uma avaliação no código e ver a possibilidade de aceitar essa modificação. A minha contribuição foi um exemplo de requisição para API em PHP, segue o link: https://github.com/edumucelli/cepaberto-api-examples/pull/20.

**Comment by edumucelli** [comment]
Obrigado @FernandoCelmer ! Merged!
