### ISSUE TITLE
HTTP Token: Access denied.

### ISSUE THREAD

**Issue by jmellodev** [edumucelli/cepaberto-api-examples#26]
Primeiro agradecer por esta maravilhosa ferramenta que é o CEP Aberto.

Acabei de criar a conta e pegar o token, porém em teste já me acesso negado, testei em PHP, Dart, Javascript e até os seus exemplos, porém, o único que responde corretamente é o Thunder Client do VS Code.

Adicionei até mesmo os Headers do Thunder na requisição da aplicação, mas mesmo assim acontece o erro.
![cepphp](https://user-images.githubusercontent.com/112833132/223004303-f8ee092b-5284-40e0-aeef-1003709c5969.png)
![thunder](https://user-images.githubusercontent.com/112833132/223004308-d0c9a2a5-3cd3-4023-b1a0-2107cc1e2585.png)

**Comment by edumucelli** [comment]
O exemplo da documentação funciona pra mim:

```
import requests

url = "https://www.cepaberto.com/api/v3/cep?cep=01001000"
headers = {'Authorization': 'Token token=<token>'}
response = requests.get(url, headers=headers)

print(response.json())
```

```
{'altitude': 760.0, 'cep': '01001000', 'latitude': '-23.5479099981', 'longitude': '-46.636', 'logradouro': 'Praça da Sé', 'bairro': 'Sé', 'complemento': '- lado ímpar', 'cidade': {'ddd': 11, 'ibge': '3550308', 'nome': 'São Paulo'}, 'estado': {'sigla': 'SP'}}
```

**Comment by edumucelli** [comment]
Re-abra caso não ainda não funcione.
