### ISSUE TITLE
Cadastrar/Atualizar CEP: 35500-000

### ISSUE THREAD

**Issue by fhariano** [edumucelli/cepaberto-api-examples#27]
O CEP acima não existe no retorno da API e consultando os Correios houve mudança deste CEP, segue print:

![image](https://github.com/edumucelli/cepaberto-api-examples/assets/7996929/238c03f1-1531-4994-8931-d9a30ac3f132)

**Comment by edumucelli** [comment]
No CEPAberto você pode entrar o CEP que falta [aqui](https://www.cepaberto.com/ceps/refresh) e clicar em "Atualizar". Fiz e agora o CEP indicado [está cadastrado](https://www.cepaberto.com/ceps/399881). Qualquer um pode fazer isso diretamente pelo site da mesma maneira.
