### ISSUE TITLE
nao consigo usar com postman

### ISSUE THREAD

**Issue by brizzio** [edumucelli/cepaberto-api-examples#4]
parece que o meu token nao é valido... é preciso ativer esse token de outra maneira?

**Comment by kelvindules** [comment]
@brizzio  Como está enviando o header? Atenção para o formato ``Token token=SeuToken``

**Comment by alexandrekumagae** [comment]
@brizzio Estava com esse mesmo "problema", segui o tutorial desse link "https://github.com/hokaccha/node-jwt-simple/issues/58", só trocar o JWT por Token..

**Comment by marcosnakamine** [comment]
![cep_aberto](https://user-images.githubusercontent.com/1054003/43285921-df7026e0-90f6-11e8-904c-e8ed7c713bda.jpg)

@brizzio, fiz o que o @kelvindules disse e funcionou
