### ISSUE TITLE
Erro 400

### ISSUE THREAD

**Issue by thiagoluis** [edumucelli/cepaberto-api-examples#5]
**curl -I -X GET -H "Token token: xpto" http://www.cepaberto.com/api/v3/cep?cep=40010000**

HTTP/1.1 400 Bad Request
Date: Sun, 08 Apr 2018 16:24:47 GMT
Server: Apache/2.4.25 (Debian)
Content-Length: 305
Connection: close
Content-Type: text/html; charset=iso-8859-1

**Comment by edumucelli** [comment]
Não deve ser uma problema ainda. Se ainda for reabro o issue.
